variables:
  GIT_SUBMODULE_STRATEGY: normal
  DOCKER_IMAGE: $CI_REGISTRY/$CI_PROJECT_PATH:test

include:
- template: Jobs/Code-Quality.gitlab-ci.yml
- template: Jobs/Build.gitlab-ci.yml
- template: Jobs/Secret-Detection.gitlab-ci.yml
- template: DAST.gitlab-ci.yml
- template: Security/Container-Scanning.gitlab-ci.yml
- local: /templates/docker-buildx.yml
stages:
- build
- test
- dast
- build_x_push

# add after_script to build to get label info
build:
  variables:
    CI_COMMIT_TAG: test
  after_script:
    - ./container-scripts/get-label-info.sh
  artifacts:
    reports:
      dotenv: build.env
