variables:
  GIT_SUBMODULE_STRATEGY: "normal"
  DOCKER_IMAGE: "$CI_REGISTRY/$CI_PROJECT_PATH:test"

include:
- project: container-email/resources/gitlab-templates
  ref: main
  file: test.yml
- project: container-email/resources/gitlab-templates
  ref: main
  file: docker-buildx.yml
- project: container-email/resources/gitlab-templates
  ref: main
  file: badge-info.yml

stages:
- build
- test
- build_x_push
